// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyibNScGPlUwoMkAoXPsWlanwO8-p4YKo',
    appId: '1:7616270039:web:4714dcca11ae2b9d242a92',
    messagingSenderId: '7616270039',
    projectId: 'bookbuddies-d1db2',
    authDomain: 'bookbuddies-d1db2.firebaseapp.com',
    storageBucket: 'bookbuddies-d1db2.appspot.com',
    measurementId: 'G-K8BEFR6Y6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBykrZZvYjto9SpbbaAgHRVdqRfrlcraIc',
    appId: '1:7616270039:android:aa94b2e78cdd7751242a92',
    messagingSenderId: '7616270039',
    projectId: 'bookbuddies-d1db2',
    storageBucket: 'bookbuddies-d1db2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2-j8w638ADLmrqsQddaZzNGkKQJQ8fnQ',
    appId: '1:7616270039:ios:9297eabce542059d242a92',
    messagingSenderId: '7616270039',
    projectId: 'bookbuddies-d1db2',
    storageBucket: 'bookbuddies-d1db2.appspot.com',
    iosBundleId: 'com.example.bookBuddies',
  );
}
